services:
  - type: web
    name: chuka-connect-backend
    runtime: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        sync: false
      - key: TOTP_ISSUER
        value: ChukaConnectAdmin
      - key: MPESA_ENV
        value: sandbox
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        value: "174379"
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false
      - key: AT_USERNAME
        value: sandbox
      - key: AT_API_KEY
        sync: false
      - key: AT_SENDER_ID
        value: CHUKACONNECT
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        value: chuka_connect_webhook_verify
